---
##- include: handlers/main.yaml
- hosts: server1
  gather_facts: no
  tasks:
    - name: Test Debug
      debug: msg={{ tomcat_location }}
      changed_when: true
      notify: stop tomcat
#    - name: Configure and Start Tomcat
#      shell: /var/local/ansible/tomcat/files/tomcatconf.sh > /var/local/ansible/tomcat/tomcatconf.log &
#      args:
#         chdir:  "{{ tomcat_location }}"
 
  handlers:
  - include: handlers/main.yaml
