---

- name: Download war
  get_url: url={{ tomcatwar_src_url }} dest={{ tomcat_location }}/output/build/webapps
  args:
   validate_certs: False
  tags: [tomcat,war]

- name: Configure and Start Tomcat
  shell: /var/local/ansible/tomcat/files/tomstart.sh > /var/local/ansible/tomcat/tomstart.log &
  notify: restart tomcat
  tags: [tomcat,war]
##      args:
##         chdir:  "{{ tomcat_location }}"
#
#  handlers:
#  - include: handlers/main.yaml
#
